server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: 'github.com/ctillman-solstice/app-config:http://localhost:8080'
          skip-ssl-validation: true
      allow-override: true
      override-none: true
      override-system-properties: false
  application:
    name: configserver