server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: /Users/caleb/workspace/app-config
          skip-ssl-validation: true
  application:
    name: configserver
  config:
    name: configserver