server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: 'git@github.com:ctillman-solstice/app-config'
          skip-ssl-validation: true
      allow-override: true
      override-none: true
      override-system-properties: false
  application:
    name: configserver
